//go:build !chaingen
// +build !chaingen

// Code generated by chaingen. DO NOT EDIT.
package offset

import (
	"fmt"
	"golang.org/x/tools/go/packages"
	"log"
)

// Limit sets the limit
// This is a second line of the comment
func (o OffsetBuilder) Limit(limit int) OffsetBuilder {
	o.L = o.L.Limit(limit)
	return o
}

// LimitGet returns the limit
func (o OffsetBuilder) LimitGet() int {
	return o.L.GetLimit()
}

func (o OffsetBuilder) LimitChainMethodWithExternalType(param1 *log.Logger, param2 packages.Module) OffsetBuilder {
	o.L = o.L.ChainMethodWithExternalType(param1, param2)
	return o
}

func (o OffsetBuilder) LimitFinalizerWithExternalType(param1 fmt.Formatter, param2 packages.Package) packages.Package {
	return o.L.FinalizerWithExternalType(param1, param2)
}

func (o OffsetBuilder) LimitprivateChainingMethod() OffsetBuilder {
	o.L = o.L.privateChainingMethod()
	return o
}

func (o OffsetBuilder) LimitVariadicMethod(params ...string) OffsetBuilder {
	o.L = o.L.VariadicMethod(params...)
	return o
}
