//go:build !chaingen
// +build !chaingen

// Code generated by chaingen. DO NOT EDIT.

package offset

import (
	"fmt"
	"golang.org/x/tools/go/packages"
	"log"
)

// Limit sets the limit
// This is a second line of the comment
func (o OffsetBuilder) Limit(limit int) OffsetBuilder {
	o.L = o.L.Limit(limit)
	return o
}

// GetLimit returns the limit
func (o OffsetBuilder) GetLimit() int {
	return o.L.GetLimit()
}

func (o OffsetBuilder) ChainMethodWithExternalType(param1 *log.Logger, param2 packages.Module) OffsetBuilder {
	o.L = o.L.ChainMethodWithExternalType(param1, param2)
	return o
}

func (o OffsetBuilder) FinalizerWithExternalType(param1 fmt.Formatter, param2 packages.Package) packages.Package {
	return o.L.FinalizerWithExternalType(param1, param2)
}

func (o OffsetBuilder) privateChainingMethod() OffsetBuilder {
	o.L = o.L.privateChainingMethod()
	return o
}

func (o OffsetBuilder) VariadicMethod(params ...string) OffsetBuilder {
	o.L = o.L.VariadicMethod(params...)
	return o
}
