//go:build !chaingen
// +build !chaingen

// Code generated by chaingen. DO NOT EDIT.
package sql_builder

import (
	"fmt"
	"github.com/AnatolyRugalev/chaingen/examples/sql_builder/offset"
	"golang.org/x/tools/go/packages"
	"log"
)

// Where sets SQL condition
func (s SQLBuilder) Where(condition string) SQLBuilder {
	s.W = s.W.Where(condition)
	return s
}

// OffsetLimit sets the limit
// This is a second line of the comment
func (s SQLBuilder) OffsetLimit(limit int) SQLBuilder {
	s.O = s.O.Limit(limit)
	return s
}

// OffsetLimitGet returns the limit
func (s SQLBuilder) OffsetLimitGet() int {
	return s.O.LimitGet()
}

func (s SQLBuilder) OffsetLimitChainMethodWithExternalType(param1 *log.Logger, param2 packages.Module) SQLBuilder {
	s.O = s.O.LimitChainMethodWithExternalType(param1, param2)
	return s
}

func (s SQLBuilder) OffsetLimitFinalizerWithExternalType(param1 fmt.Formatter, param2 packages.Package) packages.Package {
	return s.O.LimitFinalizerWithExternalType(param1, param2)
}

func (s SQLBuilder) OffsetLimitVariadicMethod(params ...string) SQLBuilder {
	s.O = s.O.LimitVariadicMethod(params...)
	return s
}

// Offset sets the offset param
func (s SQLBuilder) Offset(offset int) SQLBuilder {
	s.O = s.O.Offset(offset)
	return s
}

func (s SQLBuilder) OffsetGet() int {
	return s.O.GetOffset()
}

// OffsetFinalizer is a useless finalizer that returns pointer to the builder
func (s SQLBuilder) OffsetFinalizer() *offset.OffsetBuilder {
	return s.O.Finalizer()
}
